[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$OpnUrl,
  [string]$WanId = 'wan',
  [string[]]$LanIds = @('lan'),
  [int]$PrefixDelegationSize = 64,
  [switch]$RequestPrefixOnly,
  [switch]$SendPrefixHint,
  [hashtable]$PrefixIdMap = @{ 'lan' = '0' },
  [switch]$PreventRelease,
  [int]$VerifyPingCount = 3,
  [string]$CredFile = (Join-Path $PSScriptRoot 'OPNsense.localdomain_root_apikey.txt'),
  [string]$ApiKey = '',
  [string]$ApiSecret = '',
  [switch]$SkipCertificateCheck,
  [switch]$SelfTest,
  [switch]$AddFirewallRules,
  [switch]$NoCache,
  [string]$GatewayMonitorV6 = '2606:4700:4700::1111',
  [switch]$AutoSetGatewayMonitor,
  [hashtable]$GatewayMonitorMap = @{},
  [switch]$ShowRouteV6
)
$ErrorActionPreference = 'Stop'
function Get-OpnCredsFromFile { param([Parameter(Mandatory=$true)][string]$Path) if (-not (Test-Path -LiteralPath $Path)) { throw "Credential file not found: $Path" } $key = $null; $secret = $null; $lines = Get-Content -LiteralPath $Path -Raw -ErrorAction Stop -Encoding UTF8; foreach ($line in ($lines -split "`r?`n")) { if ($line -match '^\s*#') { continue }; if ($line -match '^\s*$') { continue }; if ($line -match '^\s*key\s*=\s*(.+)\s*$') { $key = $Matches[1].Trim(); continue }; if ($line -match '^\s*secret\s*=\s*(.+)\s*$') { $secret = $Matches[1].Trim(); continue } }; if ([string]::IsNullOrWhiteSpace($key) -or [string]::IsNullOrWhiteSpace($secret)) { throw "Credential file missing 'key=' or 'secret=' entries." }; [PSCustomObject]@{ Key = $key; Secret = $secret } }
if ([string]::IsNullOrWhiteSpace($ApiKey) -or [string]::IsNullOrWhiteSpace($ApiSecret)) { $creds = Get-OpnCredsFromFile -Path $CredFile; $ApiKey = $creds.Key; $ApiSecret = $creds.Secret }
$basicAuth = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("${ApiKey}:${ApiSecret}"))
$CommonHeaders = @{ Accept = 'application/json'; Authorization = $basicAuth; 'X-Requested-With' = 'XMLHttpRequest'; 'Content-Type' = 'application/json' }
$RestCommon = @{ Headers = $CommonHeaders }
$script:__irmSkipParam = (Get-Command Invoke-RestMethod).Parameters.ContainsKey('SkipCertificateCheck')
$script:__iwrSkipParam = (Get-Command Invoke-WebRequest).Parameters.ContainsKey('SkipCertificateCheck')
if ($SkipCertificateCheck -and $script:__irmSkipParam -and $script:__iwrSkipParam) { $RestCommon['SkipCertificateCheck'] = $true }
$GetCache = @{}
$script:InterfaceSnapshot = $null
function Invoke-WithTlsBypassIRM { param([scriptblock]$Action) if ($SkipCertificateCheck -and -not $script:__irmSkipParam) { $orig = [System.Net.ServicePointManager]::ServerCertificateValidationCallback; try { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }; & $Action } finally { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = $orig } } else { & $Action } }
function Invoke-WithTlsBypassIWR { param([scriptblock]$Action) if ($SkipCertificateCheck -and -not $script:__iwrSkipParam) { $orig = [System.Net.ServicePointManager]::ServerCertificateValidationCallback; try { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }; & $Action } finally { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = $orig } } else { & $Action } }
function Invoke-OpnApi { param([ValidateSet('GET','POST')][string]$Method,[string]$Path,[Parameter(ValueFromPipeline=$true)]$Body = $null,[switch]$CacheableGet) $uri = if ($Path -like 'http*') { $Path } else { ($OpnUrl.TrimEnd('/')) + $Path }; if ($Method -eq 'GET' -and $CacheableGet -and -not $NoCache) { if ($GetCache.ContainsKey($uri)) { return $GetCache[$uri] } } $opts = @{ Method = $Method; Uri = $uri; Headers = $CommonHeaders; ErrorAction = 'Stop' }; if ($SkipCertificateCheck -and $script:__irmSkipParam) { $opts['SkipCertificateCheck'] = $true }; if ($Method -eq 'POST') { if ($null -eq $Body) { $Body = @{} }; $json = if ($Body -is [string]) { $Body } else { $Body | ConvertTo-Json -Depth 12 }; $opts['ContentType'] = 'application/json'; $opts['Body'] = $json } try { $resp = Invoke-WithTlsBypassIRM { Invoke-RestMethod @opts }; $out = [pscustomobject]@{ StatusCode = 200; Json = $resp; Ok = $true } } catch { $ex = $_.Exception; $status = if ($ex.Response -and $ex.Response.StatusCode) { [int]$ex.Response.StatusCode } else { -1 }; $out = [pscustomobject]@{ StatusCode = $status; Json = $null; Ok = $false } } if ($Method -eq 'GET' -and $CacheableGet -and $out.Ok -and -not $NoCache) { $GetCache[$uri] = $out } return $out }
function Test-ApiPresence { param([Parameter(Mandatory=$true)][string]$Path,[ValidateSet('GET','POST','OPTIONS')][string]$Method='GET') $uri = "{0}{1}" -f $OpnUrl.TrimEnd('/'), $Path; try { $resp = Invoke-WithTlsBypassIWR { switch ($Method) { 'GET' { Invoke-WebRequest -Method Get -Uri $uri @RestCommon -TimeoutSec 20 }; 'POST' { Invoke-WebRequest -Method Post -Uri $uri -Body '{}' -ContentType 'application/json' @RestCommon -TimeoutSec 20 }; 'OPTIONS' { Invoke-WebRequest -Method Options -Uri $uri @RestCommon -TimeoutSec 20 } } }; [pscustomobject]@{ path=$Path; method=$Method; status=$resp.StatusCode; exists=$true } } catch { $resp = $_.Exception.Response; $code = if ($resp -and $resp.StatusCode) { [int]$resp.StatusCode } else { -1 }; $exists = ($code -gt 0 -and $code -ne 404); [pscustomobject]@{ path=$Path; method=$Method; status=$code; exists=$exists } } }
function Get-PreferredV6PingTarget { $g = Get-GatewayStatusJson; $mon=''; if ($g) { $items = @(); if ($g.rows) { $items = $g.rows } elseif ($g -is [array]) { $items = $g } else { $items = @($g) }; $v6 = @($items | Where-Object { (($_.af -eq 'inet6') -or ($_.ipprotocol -eq 'inet6') -or ($_.proto -eq 'inet6') -or ($_.gateway -match ':')) }); if ($v6.Count -gt 0) { foreach ($mp in @('monitor','monitor_ip','monitorip','monitor_address')) { if ($v6[0].PSObject.Properties.Name -contains $mp) { $mon = [string]$v6[0].$mp; if ($mon) { break } } } } }; if ([string]::IsNullOrWhiteSpace($mon)) { if ($GatewayMonitorV6 -and $GatewayMonitorV6.Trim().Length -gt 0) { $mon = $GatewayMonitorV6 } else { $mon = 'ipv6.google.com' } }; return $mon }
function Run-PingSelfTest { param([int]$Count = 1) try { $probe = Test-ApiPresence -Path '/api/diagnostics/ping/set' -Method POST; if (-not $probe.exists) { return [pscustomobject]@{ path='/api/diagnostics/ping/*'; ok=$false; output='ping api not available' } }; $cfg = Invoke-OpnApi -Method POST -Path '/api/diagnostics/ping/set' -Body @{ hostname=(Get-PreferredV6PingTarget); count=$Count; size=56; ipproto='inet6'; source='' }; if (-not $cfg.Ok) { return [pscustomobject]@{ path='/api/diagnostics/ping/*'; ok=$false; output='ping set failed' } }; Invoke-OpnApi -Method POST -Path ('/api/diagnostics/ping/start/' + $cfg.Json.jobid) | Out-Null; Start-Sleep -Seconds 2; $res = Invoke-OpnApi -Method GET -Path '/api/diagnostics/ping/get'; $out = if ($res.Ok -and $res.Json.rows -and $res.Json.rows.data) { $res.Json.rows.data -join "`n" } elseif ($res.Ok -and $res.Json.output) { [string]$res.Json.output } else { '' }; [pscustomobject]@{ path='/api/diagnostics/ping/*'; ok=($out -match 'bytes from'); output=$out } } catch { [pscustomobject]@{ path='/api/diagnostics/ping/*'; ok=$false; output="Ping test failed: $($_.Exception.Message)" } } }
function Get-InterfaceSnapshot { param([switch]$Force) if ($Force) { $keys = @($GetCache.Keys); foreach ($k in $keys) { if ($k -like '*interfaces_info*') { $null = $GetCache.Remove($k) } } }; $r = Invoke-OpnApi -Method GET -Path '/api/interfaces/overview/interfaces_info?details=true' -CacheableGet; if (-not $r.Ok) { throw "Failed to fetch interfaces_info (HTTP $($r.StatusCode))." }; $rows = @(); if ($r.Json.rows) { $rows = $r.Json.rows } elseif ($r.Json -is [array]) { $rows = $r.Json } else { $rows = @($r.Json) }; $nameSet = New-Object System.Collections.Generic.HashSet[string]; foreach ($row in $rows) { foreach ($p in $row.PSObject.Properties) { $val = [string]$p.Value; if ($val -and ($val -match '^(wan|lan|opt[0-9]+)$')) { $null = $nameSet.Add($val) } } }; $snap = [pscustomobject]@{ names = @($nameSet); rows = $rows; info = $r.Json }; $script:InterfaceSnapshot = $snap; return $snap }
function Confirm-Interfaces { $snap = if ($script:InterfaceSnapshot) { $script:InterfaceSnapshot } else { Get-InterfaceSnapshot }; $ids = @($WanId) + $LanIds; foreach ($id in $ids) { if (-not ($snap.names -contains $id)) { throw "Interface identifier '$id' not found. Available: $([string]::Join(', ', ($snap.names | Select-Object -Unique)))" } }; $snap.info }
function Discover-LanIds { param([string]$Wan) $snap = if ($script:InterfaceSnapshot) { $script:InterfaceSnapshot } else { Get-InterfaceSnapshot }; $list = @($snap.names | Where-Object { $_ -ne $Wan -and ($_ -match '^(lan|opt[0-9]+)$') }); $list = @($list | Sort-Object { if ($_ -eq 'lan') { -1 } else { [int]($_ -replace '^opt','') } }); if ($list.Count -eq 0) { return @('lan') } else { return ,$list } }
function Apply-Services { param([string[]]$IfsToReload) foreach ($if in $IfsToReload) { try { Invoke-OpnApi -Method GET -Path "/api/interfaces/overview/reload_interface/$if" | Out-Null } catch {} }; try { Invoke-OpnApi -Method POST -Path '/api/dhcpv6/service/reconfigure' -Body @{} | Out-Null } catch {} }
function Verify-IPv6 { param([int]$Count = 3) $set = @{ hostname=(Get-PreferredV6PingTarget); count=$Count; size=56; source=''; ipproto='inet6' }; try { $cfg = Invoke-OpnApi -Method POST -Path '/api/diagnostics/ping/set' -Body $set; if ($cfg.Ok) { Invoke-OpnApi -Method POST -Path ('/api/diagnostics/ping/start/' + $cfg.Json.jobid) | Out-Null; Start-Sleep -Seconds 2; $res = Invoke-OpnApi -Method GET -Path '/api/diagnostics/ping/get'; if ($res.Ok -and $res.Json.rows -and $res.Json.rows.data) { $res.Json.rows.data -join "`n" } elseif ($res.Ok -and $res.Json.output) { [string]$res.Json.output } else { '' } } else { '' } } catch { '' } }
function Coerce-BoolString([bool]$v) { if ($v) { '1' } else { '0' } }
function Validate-PrefixLen([int]$pdLen) { if ($pdLen -lt 48 -or $pdLen -gt 64) { throw "PD length must be between 48 and 64 (got $pdLen)." }; $neededNibbles = [int]([Math]::Max(0, [Math]::Floor((64 - $pdLen) / 4.0))); if ($neededNibbles -gt 4) { throw "Computed prefix-id nibbles > 4 ($neededNibbles) for PD /${pdLen}." }; [pscustomobject]@{ NeededNibbles = $neededNibbles } }
function Set-Wan-Dhcpv6 { param([int]$pdLen,[bool]$reqOnly,[bool]$sendHint,[bool]$iana) $payloadA = @{ $WanId = @{ ipv6 = 'dhcp6'; dhcp6_requestprefixonly = (Coerce-BoolString $reqOnly); dhcp6_sendprefixhint = (Coerce-BoolString $sendHint); dhcp6_iana = (Coerce-BoolString $iana); dhcp6_prefixdelegation = "$pdLen" } }; $payloadB = @{ $WanId = @{ ipv6 = 'dhcp6'; requestprefixonly = (Coerce-BoolString $reqOnly); sendprefixhint = (Coerce-BoolString $sendHint); iana = (Coerce-BoolString $iana); prefixdelegation = "$pdLen" } }; $ok = $false; $r1 = Invoke-OpnApi -Method POST -Path '/api/interfaces/ifsettings/set' -Body $payloadA; if ($r1.Ok -or $r1.StatusCode -in 200,201) { $ok = $true }; if (-not $ok -and $r1.StatusCode -eq 404) { $r2 = Invoke-OpnApi -Method POST -Path '/api/interfaces/settings/set' -Body $payloadB; if ($r2.Ok -or $r2.StatusCode -in 200,201) { $ok = $true } }; [void](Invoke-OpnApi -Method GET -Path "/api/interfaces/overview/reload_interface/$WanId"); return $ok }
function Set-Lan-Track6 { param([string]$lanId,[int]$pdLen,[string]$prefixIdHex) $v = Validate-PrefixLen -pdLen $pdLen; if ($prefixIdHex.Length -gt $v.NeededNibbles -and $v.NeededNibbles -gt 0) { throw "track6_prefix_id too long for PD /${pdLen}: '$prefixIdHex'" }; $payloadA = @{ $lanId = @{ ipv6 = 'track6'; track6_interface = $WanId; track6_prefix_id = $prefixIdHex } }; $payloadB = @{ $lanId = @{ ipv6 = 'track6'; track6_interface = $WanId; track6_prefix_id_hex = $prefixIdHex } }; $ok = $false; $r1 = Invoke-OpnApi -Method POST -Path '/api/interfaces/ifsettings/set' -Body $payloadA; if ($r1.Ok -or $r1.StatusCode -in 200,201) { $ok = $true }; if (-not $ok -and $r1.StatusCode -eq 404) { $r2 = Invoke-OpnApi -Method POST -Path '/api/interfaces/settings/set' -Body $payloadB; if ($r2.Ok -or $r2.StatusCode -in 200,201) { $ok = $true } }; [void](Invoke-OpnApi -Method GET -Path "/api/interfaces/overview/reload_interface/$lanId"); return $ok }
function Set-RA-Assisted { param([string]$lanId) $payloadNew = @{ $lanId = @{ RouterAdvertisements = 'assisted'; AdvPriority = 'normal' } }; $payloadOld = @{ $lanId = @{ router_advertisements = 'assisted'; priority = 'normal' } }; $ok = $false; $s1 = Invoke-OpnApi -Method POST -Path '/api/dhcpv6/router_advertisements/set' -Body $payloadNew; if ($s1.Ok -or $s1.StatusCode -in 200,201) { $ok = $true }; if (-not $ok -and $s1.StatusCode -eq 404) { $s2 = Invoke-OpnApi -Method POST -Path '/api/dhcp/router_advertisements/set' -Body $payloadOld; if ($s2.Ok -or $s2.StatusCode -in 200,201) { $ok = $true } }; [void](Invoke-OpnApi -Method POST -Path '/api/dhcpv6/service/reconfigure' -Body @{}); return $ok }
function Rule-Exists { param([string]$descr) $q = Invoke-OpnApi -Method POST -Path '/api/firewall/filter/searchRule' -Body @{}; if (-not $q.Ok) { return $false }; $rows = @(); if ($q.Json.rows) { $rows = $q.Json.rows } elseif ($q.Json -is [array]) { $rows = $q.Json } else { $rows = @($q.Json) }; foreach ($r in $rows) { if ($r.description -eq $descr -or $r.descr -eq $descr) { return $true } }; return $false }
function Add-IPv6-FirewallRules { param([string]$lanId) $allowAnyDescr = "[auto] IPv6 LAN any ($lanId)"; if (-not (Rule-Exists -descr $allowAnyDescr)) { $body = @{ rule = @{ enabled = '1'; descr = $allowAnyDescr; action = 'pass'; type='pass'; interface = $lanId; ipprotocol = 'inet6'; protocol = 'any'; source = @{ address = "${lanId}_net" }; destination = @{ any = '1' }; log = '0' } }; [void](Invoke-OpnApi -Method POST -Path '/api/firewall/filter/addRule' -Body $body) }; $icmpDescr = "[auto] IPv6 ICMPv6 ($lanId)"; if (-not (Rule-Exists -descr $icmpDescr)) { $body2 = @{ rule = @{ enabled = '1'; descr = $icmpDescr; action = 'pass'; type='pass'; interface = $lanId; ipprotocol = 'inet6'; protocol = 'icmp'; icmp6type = 'any'; source = @{ address = "${lanId}_net" }; destination = @{ any = '1' }; log = '0' } }; [void](Invoke-OpnApi -Method POST -Path '/api/firewall/filter/addRule' -Body $body2) }; [void](Invoke-OpnApi -Method POST -Path '/api/firewall/filter/apply' -Body @{}) }
function Get-IPv6AddrsFromRow { param($row) $addrs = @(); foreach ($prop in @('inet6','addresses','ipv6')) { if ($row.PSObject.Properties.Name -contains $prop) { $v = $row.$prop; if ($v -is [System.Collections.IEnumerable]) { foreach ($x in $v) { if ($x -is [string]) { if ($x -match '([0-9a-fA-F:]{2,})') { $addrs += $matches[1] } } elseif ($x.PSObject.Properties.Name -contains 'address') { $addrs += [string]$x.address } } } elseif ($v -is [string]) { if ($v -match '([0-9a-fA-F:]{2,})') { $addrs += $matches[1] } } } } $addrs = $addrs | Where-Object { $_ -match ':' } | Select-Object -Unique; return ,$addrs }
function Verify-PostApply { param([string]$Wan,[string[]]$LanList,[string]$PingOut) $snap = Get-InterfaceSnapshot -Force; $wanRow = $snap.rows | Where-Object { $m=$false; foreach($p in $_.PSObject.Properties){ if([string]$p.Value -eq $Wan){ $m=$true; break } }; $m } | Select-Object -First 1; $wanAddrs = @(); if ($wanRow) { $wanAddrs = Get-IPv6AddrsFromRow $wanRow }; $wanLL = @($wanAddrs | Where-Object { $_ -like 'fe80::*' -or $_ -like 'fe80:*' }); $wanGua = @($wanAddrs | Where-Object { ($_ -notmatch '^fe80:') -and ($_ -notmatch '^fd[0-9a-fA-F]') -and ($_ -notmatch '^fc[0-9a-fA-F]') }); $lanGuaCount = 0; foreach($lan in $LanList){ $row = $snap.rows | Where-Object { $m=$false; foreach($p in $_.PSObject.Properties){ if([string]$p.Value -eq $lan){ $m=$true; break } }; $m } | Select-Object -First 1; if ($row) { $la = Get-IPv6AddrsFromRow $row; $gua = @($la | Where-Object { ($_ -notmatch '^fe80:') -and ($_ -notmatch '^fd[0-9a-fA-F]') -and ($_ -notmatch '^fc[0-9a-fA-F]') }); if ($gua.Count -gt 0){ $lanGuaCount++ } } }; $pingOk = ($PingOut -and ($PingOut -match 'bytes from')); [pscustomobject]@{ WanHasIPv6 = (($wanLL.Count -gt 0) -or ($wanGua.Count -gt 0)); LanWithGUA = $lanGuaCount; LanTotal = $LanList.Count; PingOK = $pingOk } }
function Get-GatewayStatusJson { $cands = @(@{Path='/api/routes/gateway/status';Method='GET'}, @{Path='/api/routes/status/search';Method='POST'}, @{Path='/api/diagnostics/gateway/status';Method='GET'}, @{Path='/api/system/gateway/status';Method='GET'}); foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $res = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($res.Ok -and $res.Json) { return $res.Json } } }; return $null }
function Find-DefaultRouteV6 { $cands = @(@{Path='/api/routes/status/search';Method='POST'}, @{Path='/api/diagnostics/route/search';Method='POST'}, @{Path='/api/diagnostics/route/get';Method='GET'}); foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $r = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($r.Ok) { $rows = @(); if ($r.Json.rows) { $rows = $r.Json.rows } elseif ($r.Json -is [array]) { $rows = $r.Json } else { $rows = @($r.Json) }; $def = $rows | Where-Object { ($_.destination -eq '::/0' -or $_.network -eq '::/0' -or $_.destination -eq 'default' -or $_.network -eq 'default' -or $_.prefix -eq '::/0') -and (($_.af -eq 'inet6') -or ($_.ipprotocol -eq 'inet6') -or ($_.proto -eq 'inet6') -or ($_.gateway -match ':')) } | Select-Object -First 1; if ($def) { return $true } } } }; return $false }
function Verify-RoutingAndGateway { param([string]$Wan) $g = Get-GatewayStatusJson; $hasGw6 = $false; $mon = 'Unknown'; $monIp=''; $loss=''; $delay=''; if ($g) { $items = @(); if ($g.rows) { $items = $g.rows } elseif ($g -is [array]) { $items = $g } else { $items = @($g) }; $v6 = @($items | Where-Object { (($_.af -eq 'inet6') -or ($_.ipprotocol -eq 'inet6') -or ($_.proto -eq 'inet6') -or ($_.gateway -match ':')) }); if ($v6.Count -gt 0) { $hasGw6 = $true; $statusProp = @('status','monitor','status_translated') | Where-Object { $_ -in $v6[0].PSObject.Properties.Name } | Select-Object -First 1; if ($statusProp) { $mon = [string]$v6[0].$statusProp } elseif ($v6[0].loss -ne $null) { $mon = 'online' } else { $mon = 'Unknown' }; foreach ($mp in @('monitor','monitor_ip','monitorip','monitor_address')) { if ($v6[0].PSObject.Properties.Name -contains $mp) { $monIp = [string]$v6[0].$mp; if ($monIp) { break } } }; foreach ($dp in @('delay','rtt','avg_delay','latency')) { if ($v6[0].PSObject.Properties.Name -contains $dp) { $delay = [string]$v6[0].$dp; if ($delay) { break } } }; foreach ($lp in @('loss','packetloss')) { if ($v6[0].PSObject.Properties.Name -contains $lp) { $loss = [string]$v6[0].$lp; if ($loss) { break } } } } }; $def6 = Find-DefaultRouteV6; [pscustomobject]@{ DefaultV6 = $def6; GwV6Present = $hasGw6; GwMonitor = $mon; MonitorIP=$monIp; Delay=$delay; Loss=$loss } }
function Get-RuleUuids { param([string[]]$Labels) $q = Invoke-OpnApi -Method POST -Path '/api/firewall/filter/searchRule' -Body @{}; $rows = @(); if ($q.Ok) { if ($q.Json.rows) { $rows = $q.Json.rows } elseif ($q.Json -is [array]) { $rows = $q.Json } else { $rows = @($q.Json) } }; $out = @(); foreach ($lab in $Labels) { $hit = $rows | Where-Object { $_.description -eq $lab -or $_.descr -eq $lab } | Select-Object -First 1; $uuid = $null; if ($hit) { if ($hit.PSObject.Properties.Name -contains 'uuid') { $uuid = [string]$hit.uuid } elseif ($hit.PSObject.Properties.Name -contains 'ruleid') { $uuid = [string]$hit.ruleid } }; $out += [pscustomobject]@{ Description = $lab; UUID = ($uuid | ForEach-Object { if ($_ -and $_.Length -gt 0) { $_ } else { 'n/a' } }) } }; return ,$out }

function Get-WanHasGua { param([string]$Wan) $snap = Get-InterfaceSnapshot; $row = $snap.rows | Where-Object { $m=$false; foreach($p in $_.PSObject.Properties){ if([string]$p.Value -eq $Wan){ $m=$true; break } }; $m } | Select-Object -First 1; if (-not $row) { return $false }; $addrs = Get-IPv6AddrsFromRow $row; $gua = @($addrs | Where-Object { ($_ -notmatch '^fe80:') -and ($_ -notmatch '^fd[0-9a-fA-F]') -and ($_ -notmatch '^fc[0-9a-fA-F]') }); return ($gua.Count -gt 0) }
function Get-DefaultV6Gateway { $rows = @(); $cands = @(@{Path='/api/routes/status/search';Method='POST'}, @{Path='/api/diagnostics/route/search';Method='POST'}) ; foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $r = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($r.Ok) { if ($r.Json.rows) { $rows = $r.Json.rows } elseif ($r.Json -is [array]) { $rows = $r.Json } else { $rows = @($r.Json) }; break } } }; if ($rows.Count -eq 0) { return '' }; $def = $rows | Where-Object { ($_.destination -eq '::/0' -or $_.network -eq '::/0' -or $_.prefix -eq '::/0' -or $_.destination -eq 'default' -or $_.network -eq 'default') -and (($_.af -eq 'inet6') -or ($_.ipprotocol -eq 'inet6') -or ($_.proto -eq 'inet6')) } | Select-Object -First 1; if (-not $def) { return '' }; foreach ($p in @('gateway','gw','nexthop','nhop')) { if ($def.PSObject.Properties.Name -contains $p) { return [string]$def.$p } }; return '' }
function Get-GatewayRows { $cands = @(@{Path='/api/routes/gateway/searchGateway';Method='POST'}, @{Path='/api/routes/gateway/search';Method='POST'}, @{Path='/api/system/gateway/searchGateway';Method='POST'}, @{Path='/api/system/gateway/search';Method='POST'}, @{Path='/api/routes/gateway/get';Method='GET'}); foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $r = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($r.Ok -and $r.Json) { $rows = @(); if ($r.Json.rows) { $rows = $r.Json.rows } elseif ($r.Json -is [array]) { $rows = $r.Json } else { $rows = @($r.Json) }; if ($rows.Count -gt 0) { return ,$rows } } } }; return @() }
function Ensure-IPv6GatewayMonitor { param([string]$Wan,[string]$Monitor,[hashtable]$Map) $rows = Get-GatewayRows; if ($rows.Count -eq 0) { return [pscustomobject]@{ Changed=$false; Name=''; UUID=''; Monitor='' } }; $wanLower = $Wan.ToLower(); $gw = $rows | Where-Object { (($_.ipprotocol -eq 'inet6') -or ($_.af -eq 'inet6') -or ($_.gateway -match ':')) -and (([string]$_.interface).ToLower() -eq $wanLower -or ([string]$_.name -match '(?i)dhcp6') -or ([string]$_.name -match '(?i)wan.*6')) } | Select-Object -First 1; if (-not $gw) { $gw = $rows | Where-Object { (($_.ipprotocol -eq 'inet6') -or ($_.af -eq 'inet6') -or ($_.gateway -match ':')) } | Select-Object -First 1 }; if (-not $gw) { return [pscustomobject]@{ Changed=$false; Name=''; UUID=''; Monitor='' } }; $monProp = @('monitor','monitorip','monitor_ip','monitor_address') | Where-Object { $_ -in $gw.PSObject.Properties.Name } | Select-Object -First 1; $cur = if ($monProp) { [string]$gw.$monProp } else { '' }; if ($cur -and $cur.Trim().Length -gt 0) { return [pscustomobject]@{ Changed=$false; Name=([string]$gw.name); UUID=([string]$gw.uuid); Monitor=$cur } }; $uuid = '';$name=''; foreach ($p in @('uuid','guid','id')) { if ($gw.PSObject.Properties.Name -contains $p) { $uuid = [string]$gw.$p; break } }; if ($gw.PSObject.Properties.Name -contains 'name') { $name = [string]$gw.name }; $wantMon = $Monitor; if ($Map -and $Map.ContainsKey($name)) { $wantMon = [string]$Map[$name] } else { $wanHasGua = Get-WanHasGua -Wan $Wan; if (-not $wanHasGua) { $ll = ''; foreach ($p in @('gateway','gw','nexthop','nhop')) { if ($gw.PSObject.Properties.Name -contains $p) { $ll = [string]$gw.$p; if ($ll) { break } } }; if (-not $ll) { $ll = Get-DefaultV6Gateway }; if ($ll -and $ll -like 'fe80:*') { $wantMon = $ll } } }
  $plA = @{ uuid=$uuid; gateway=@{ monitor=$wantMon } }
  $plB = @{ gateway=@{ uuid=$uuid; monitor=$wantMon } }
  $plC = @{ uuid=$uuid; monitor=$wantMon }
  $ok = $false
  foreach ($endpoint in @('/api/routes/gateway/setItem','/api/system/gateway/setItem','/api/routes/gateway/set','/api/system/gateway/set')) {
    $r = Invoke-OpnApi -Method POST -Path $endpoint -Body $plA
    if (-not $r.Ok -or ($r.StatusCode -eq 404)) { $r = Invoke-OpnApi -Method POST -Path $endpoint -Body $plB }
    if (-not $r.Ok -or ($r.StatusCode -eq 404)) { $r = Invoke-OpnApi -Method POST -Path $endpoint -Body $plC }
    if ($r.Ok -or ($r.StatusCode -in 200,201)) { $ok = $true; break }
  }
  foreach ($apply in @('/api/routes/gateway/apply','/api/system/gateway/apply','/api/routes/apply')) { try { [void](Invoke-OpnApi -Method POST -Path $apply -Body @{}) } catch {} }
  return [pscustomobject]@{ Changed=$ok; Name=($name); UUID=$uuid; Monitor=$wantMon }
}
function Get-GatewayMonMetrics { $g = Get-GatewayStatusJson; $out=@(); if ($g) { $items = @(); if ($g.rows) { $items = $g.rows } elseif ($g -is [array]) { $items = $g } else { $items = @($g) }; foreach ($r in $items) { $is6 = (($r.PSObject.Properties.Name -contains 'af' -and $r.af -eq 'inet6') -or ($r.PSObject.Properties.Name -contains 'ipprotocol' -and $r.ipprotocol -eq 'inet6') -or ($r.gateway -match ':')); if ($is6) { $name = if ($r.PSObject.Properties.Name -contains 'name') { [string]$r.name } else { '' }; $monip=''; foreach ($mp in @('monitor','monitor_ip','monitorip','monitor_address')) { if ($r.PSObject.Properties.Name -contains $mp) { $monip = [string]$r.$mp; if ($monip) { break } } }; $delay=''; foreach ($dp in @('delay','rtt','avg_delay','latency')) { if ($r.PSObject.Properties.Name -contains $dp) { $delay = [string]$r.$dp; if ($delay) { break } } }; $loss=''; foreach ($lp in @('loss','packetloss')) { if ($r.PSObject.Properties.Name -contains $lp) { $loss = [string]$r.$lp; if ($loss) { break } } }; $stat=''; foreach ($sp in @('status','monitor','status_translated')) { if ($r.PSObject.Properties.Name -contains $sp) { $stat = [string]$r.$sp; if ($stat) { break } } }; $out += [pscustomobject]@{ Name=$name; Monitor=$monip; RTTms=$delay; Loss=$loss; Status=$stat } } } }; return ,$out }

function Get-DefaultV6RouteRow { $rows = @(); $cands = @(@{Path='/api/routes/status/search';Method='POST'}, @{Path='/api/diagnostics/route/search';Method='POST'}, @{Path='/api/diagnostics/route/get';Method='GET'}); foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $r = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($r.Ok) { if ($r.Json.rows) { $rows = $r.Json.rows } elseif ($r.Json -is [array]) { $rows = $r.Json } else { $rows = @($r.Json) }; break } } }; if ($rows.Count -eq 0) { return $null }; $def = $rows | Where-Object { ($_.destination -eq '::/0' -or $_.network -eq '::/0' -or $_.destination -eq 'default' -or $_.network -eq 'default' -or $_.prefix -eq '::/0') -and (($_.af -eq 'inet6') -or ($_.ipprotocol -eq 'inet6') -or ($_.proto -eq 'inet6') -or ($_.gateway -match ':')) } | Select-Object -First 1; return $def }
function Show-RouteV6 { param([string]$Wan) $row = Get-DefaultV6RouteRow; $gw = Get-DefaultV6Gateway; $wanGua = Get-WanHasGua -Wan $Wan; $ping = Get-PreferredV6PingTarget; $rows = Get-GatewayRows; $gw6 = $rows | Where-Object { (($_.ipprotocol -eq 'inet6') -or ($_.af -eq 'inet6') -or ($_.gateway -match ':')) } | Select-Object -First 1; $mon=''; $name=''; if ($gw6) { foreach ($mp in @('monitor','monitor_ip','monitorip','monitor_address')) { if ($gw6.PSObject.Properties.Name -contains $mp) { $mon = [string]$gw6.$mp; if ($mon) { break } } }; if ($gw6.PSObject.Properties.Name -contains 'name') { $name = [string]$gw6.name } }; if ($row) { $dest=''; foreach ($p in @('destination','network','prefix')) { if ($row.PSObject.Properties.Name -contains $p) { $dest = [string]$row.$p; if ($dest) { break } } }; $iface=''; foreach ($p in @('interface','if','dev')) { if ($row.PSObject.Properties.Name -contains $p) { $iface = [string]$row.$p; if ($iface) { break } } }; [pscustomobject]@{ Destination=$dest; Gateway=$gw; Interface=$iface } | Format-Table -AutoSize | Out-String | Write-Host }; [pscustomobject]@{ PingTarget=$ping; WAN_has_GUA=$wanGua; GW_Name=$name; GW_Monitor=$mon } | Format-Table -AutoSize | Out-String | Write-Host }
function Get-Prop { param($obj,[string[]]$names) foreach ($n in $names) { if ($obj.PSObject.Properties.Name -contains $n) { return [string]$obj.$n } } return '' }
function Get-NdpRows { $cands = @(@{Path='/api/diagnostics/ndp/search';Method='POST'}, @{Path='/api/diagnostics/interface/searchNdp';Method='POST'}, @{Path='/api/diagnostics/interface/ndp';Method='GET'}, @{Path='/api/diagnostics/ndp/get';Method='GET'}); foreach ($c in $cands) { $pr = Test-ApiPresence -Path $c.Path -Method $c.Method; if ($pr.exists) { $r = Invoke-OpnApi -Method $c.Method -Path $c.Path -Body @{}; if ($r.Ok -and $r.Json) { if ($r.Json.rows) { return ,$r.Json.rows } elseif ($r.Json -is [array]) { return ,$r.Json } else { return ,@($r.Json) } } } }; return @() }
function Show-NdpV6 { param([string]$Wan,[string]$Target) $rows = Get-NdpRows; if ($rows.Count -eq 0) { return }; $targetRow = $rows | Where-Object { (Get-Prop $_ @('ip','ipaddress','address','dst','neighbor','ipv6')) -eq $Target } | Select-Object -First 1; if ($targetRow) { [pscustomobject]@{ Scope='NDP target'; IP=(Get-Prop $targetRow @('ip','ipaddress','address','dst','neighbor','ipv6')); MAC=(Get-Prop $targetRow @('lladdr','mac','macaddress','linklayer')); Iface=(Get-Prop $targetRow @('interface','if','dev')); State=(Get-Prop $targetRow @('state','flags','status','reach')) } | Format-Table -AutoSize | Out-String | Write-Host }; $wanRows = $rows | Where-Object { (Get-Prop $_ @('interface','if','dev')) -eq $Wan }; if ($wanRows.Count -gt 0) { $wanRows | ForEach-Object { [pscustomobject]@{ Scope='NDP WAN'; IP=(Get-Prop $_ @('ip','ipaddress','address','dst','neighbor','ipv6')); MAC=(Get-Prop $_ @('lladdr','mac','macaddress','linklayer')); Iface=(Get-Prop $_ @('interface','if','dev')); State=(Get-Prop $_ @('state','flags','status','reach')) } } | Format-Table -AutoSize | Out-String | Write-Host } }
if ($PSBoundParameters.ContainsKey('LanIds')) { $LanIds = @($LanIds | ForEach-Object { $_ -split ',' } | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }); if (-not $LanIds -or $LanIds.Count -eq 0) { $LanIds = Discover-LanIds -Wan $WanId } } else { $LanIds = Discover-LanIds -Wan $WanId }
$sendHint = if ($PSBoundParameters.ContainsKey('SendPrefixHint')) { [bool]$SendPrefixHint } else { $true }
if ($SelfTest) { Write-Host ">> SelfTest: using credentials from $CredFile"; $checks = New-Object System.Collections.Generic.List[object]; try { $r = Invoke-OpnApi -Method GET -Path '/api/interfaces/overview/interfaces_info' -CacheableGet; $checks.Add([pscustomobject]@{ path='/api/interfaces/overview/interfaces_info'; method='GET'; status=if($r.Ok){200}else{$r.StatusCode}; exists=$r.Ok }) } catch { $checks.Add([pscustomobject]@{ path='/api/interfaces/overview/interfaces_info'; method='GET'; status=-1; exists=$false }) }; $checks.Add((Test-ApiPresence -Path "/api/interfaces/overview/reload_interface/$WanId" -Method GET)); $checks.Add((Test-ApiPresence -Path '/api/dhcpv6/service/reconfigure' -Method POST)); $checks.Add((Test-ApiPresence -Path '/api/firewall/filter/searchRule' -Method POST)); $checks.Add((Test-ApiPresence -Path '/api/firewall/filter/addRule' -Method POST)); $checks.Add((Test-ApiPresence -Path '/api/firewall/filter/apply' -Method POST)); $table = $checks | Select-Object @{n='Path';e={$_.path}}, @{n='Method';e={$_.method}}, @{n='Status';e={$_.status}}, @{n='Exists';e={$_.exists}}; $table | Format-Table -AutoSize | Out-String | Write-Host; $pingTest = Run-PingSelfTest -Count 1; if ($pingTest.ok) { Write-Host 'Diagnostics ping OK (IPv6):' } else { Write-Warning 'Diagnostics ping failed.' }; if ($pingTest.output) { Write-Host ($pingTest.output -replace "`r?`n$",'') }; $okOverview = ($checks | Where-Object { $_.path -eq '/api/interfaces/overview/interfaces_info' -and $_.exists }) -ne $null; $okReload = ($checks | Where-Object { $_.path -like '/api/interfaces/overview/reload_interface/*' -and $_.exists }) -ne $null; $okReconf = ($checks | Where-Object { $_.path -eq '/api/dhcpv6/service/reconfigure' -and $_.exists }) -ne $null; $okFwSearch = ($checks | Where-Object { $_.path -eq '/api/firewall/filter/searchRule' -and $_.exists }) -ne $null; $okFwAdd = ($checks | Where-Object { $_.path -eq '/api/firewall/filter/addRule' -and $_.exists }) -ne $null; $okFwApply = ($checks | Where-Object { $_.path -eq '/api/firewall/filter/apply' -and $_.exists }) -ne $null; $fwRequired = $AddFirewallRules.IsPresent; $okFw = if ($fwRequired) { $okFwSearch -and $okFwAdd -and $okFwApply } else { $true }; if ($okOverview -and $okReload -and $okReconf -and $okFw) { Write-Host '✅ SelfTest PASS: core APIs reachable (no config was changed).'; exit 0 } else { Write-Warning '❌ SelfTest FAIL: one or more required endpoints are missing or unreachable.'; exit 2 } }
Write-Host ">> OPNsense IPv6 setup – using credentials from file: $CredFile"
$null = Confirm-Interfaces
if ($PrefixDelegationSize -lt 48 -or $PrefixDelegationSize -gt 64) { throw 'PrefixDelegationSize must be between 48 and 64.' }
$reqPrefixOnly = $RequestPrefixOnly.IsPresent
$autoIdx = 0
$neededNibbles = [Math]::Ceiling((64 - [int]$PrefixDelegationSize) / 4.0)
if ($neededNibbles -lt 1) { $neededNibbles = 1 }
if ($neededNibbles -gt 4) { $neededNibbles = 4 }
$normMap = @{}
foreach ($lan in $LanIds) { if ($PrefixIdMap.ContainsKey($lan)) { $v = [string]$PrefixIdMap[$lan]; $v = ($v -replace '^0x','').ToLower(); $normMap[$lan] = $v.PadLeft($neededNibbles,'0') } else { $normMap[$lan] = ([string]([Convert]::ToString($autoIdx,16))).PadLeft($neededNibbles,'0') }; $autoIdx++ }
$wanOk = Set-Wan-Dhcpv6 -pdLen $PrefixDelegationSize -reqOnly:$reqPrefixOnly -sendHint:$sendHint -iana:(!$reqPrefixOnly)
$lanOkAll = $true
$raOkAll = $true
foreach ($lan in $LanIds) { $lanOk = Set-Lan-Track6 -lanId $lan -pdLen $PrefixDelegationSize -prefixIdHex $normMap[$lan]; if (-not $lanOk) { $lanOkAll = $false }; $raOk = Set-RA-Assisted -lanId $lan; if (-not $raOk) { $raOkAll = $false }; if ($AddFirewallRules) { Add-IPv6-FirewallRules -lanId $lan } }
if ($PreventRelease.IsPresent) { try { Invoke-OpnApi -Method POST -Path '/api/interfaces/settings/set' -Body @{ dhcp6_preventrelease = '1' } | Out-Null } catch {} }
Apply-Services -IfsToReload (@($WanId) + $LanIds)
$autoSetMon = if ($PSBoundParameters.ContainsKey('AutoSetGatewayMonitor')) { $AutoSetGatewayMonitor.IsPresent } else { $true }
if ($autoSetMon) { try { $gwSet = Ensure-IPv6GatewayMonitor -Wan $WanId -Monitor $GatewayMonitorV6 -Map $GatewayMonitorMap } catch {} }
Write-Host '>> Waiting for DHCPv6-PD...'
Start-Sleep -Seconds 6
try { $snap = Get-InterfaceSnapshot -Force; if ($snap.rows -and $snap.rows.Count -gt 0) { $wanRow = $snap.rows | Where-Object { $m = $false; foreach ($p in $_.PSObject.Properties) { if ([string]$p.Value -eq $WanId) { $m = $true; break } }; $m } | Select-Object -First 1; if ($wanRow) { $wanView = $wanRow | ConvertTo-Json -Depth 6; Write-Host 'WAN overview (trimmed):'; Write-Host ($wanView.Substring(0, [Math]::Min($wanView.Length, 600))) } } else { $wanViewObj = ($snap.info.PSObject.Properties | Where-Object Name -eq $WanId).Value; if ($null -ne $wanViewObj) { $wanView = $wanViewObj | ConvertTo-Json -Depth 6; Write-Host 'WAN overview (trimmed):'; Write-Host ($wanView.Substring(0, [Math]::Min($wanView.Length, 600))) } } } catch {}
$pingOut = Verify-IPv6 -Count $VerifyPingCount
if ($pingOut -and ($pingOut -match 'bytes from')) { Write-Host '✅ IPv6 reachable:'; Write-Host $pingOut } else { Write-Warning 'IPv6 ping not successful yet. PDs can take a few more seconds.' }
$verifySummary = Verify-PostApply -Wan $WanId -LanList $LanIds -PingOut $pingOut
$verifySummary | Select-Object @{n='WAN IPv6';e={ if ($_.WanHasIPv6) { 'OK' } else { 'NO' } }}, @{n='LAN GUA';e={ "{0}/{1}" -f $_.LanWithGUA, $_.LanTotal }}, @{n='Ping';e={ if ($_.PingOK) { 'OK' } else { 'FAIL' } }} | Format-Table -AutoSize | Out-String | Write-Host
$rg = Verify-RoutingAndGateway -Wan $WanId
$rg | Select-Object @{n='Default v6 route';e={ if ($_.DefaultV6) { 'YES' } else { 'NO' } }}, @{n='IPv6 GW present';e={ if ($_.GwV6Present) { 'YES' } else { 'NO' } }}, @{n='Monitor IP';e={$_.MonitorIP}}, @{n='GW status';e={$_.GwMonitor}}, @{n='RTT ms';e={$_.Delay}}, @{n='Loss %';e={$_.Loss}} | Format-Table -AutoSize | Out-String | Write-Host
$gm = Get-GatewayMonMetrics
if ($gm) { $gm | Format-Table -AutoSize | Out-String | Write-Host }
if ($ShowRouteV6) { Show-RouteV6 -Wan $WanId; Show-NdpV6 -Wan $WanId -Target (Get-PreferredV6PingTarget) }
$labels = @("[auto] IPv6 LAN any ($($LanIds[0]))","[auto] IPv6 ICMPv6 ($($LanIds[0]))")
$ru = Get-RuleUuids -Labels $labels
if ($ru) { $ru | Format-Table -AutoSize | Out-String | Write-Host }
if (-not $wanOk -or -not $lanOkAll -or -not $raOkAll) { Write-Warning 'Some settings may require GUI on this OPNsense version:'; if (-not $wanOk) { Write-Host 'Interfaces → WAN:'; Write-Host '  IPv6 Configuration Type: DHCPv6'; Write-Host ("  DHCPv6: {0}Request only an IPv6 prefix; {1}Send IPv6 prefix hint; Prefix delegation size: /{2}" -f ($reqPrefixOnly ? '✓ ' : '(optional) '), ($sendHint ? '✓ ' : '(recommended) '), $PrefixDelegationSize) }; if (-not $lanOkAll) { Write-Host 'Interfaces → each LAN/VLAN:'; Write-Host '  IPv6 Configuration Type: Track Interface'; Write-Host '  IPv6 Interface: WAN'; Write-Host ("  IPv6 Prefix ID: {0}" -f (($normMap.GetEnumerator() | % { "$($_.Key)=$($_.Value)" }) -join ', ')) }; if (-not $raOkAll) { Write-Host 'Services → Router Advertisements:'; Write-Host '  Mode: Assisted (per LAN/VLAN)' } }
Write-Host '>> Done.'
